name: Terraform linting
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: Checkout source code

    - uses: hashicorp/setup-terraform@v1
      name: Setup Terraform

    - run: terraform fmt -check -recursive
      name: Terraform Format
      id: fmt

    - run: terraform init -backend=false
      name: Terraform Init

    - run: terraform validate
      name: Terraform Validate

    - uses: actions/cache@v2
      name: Cache tflint plugin dir
      with:
        path: ~/.tflint.d/plugins
        key: ${{ matrix.os }}-tflint-${{ hashFiles('.tflint.hcl') }}

    - name: Setup TFLint
      uses: terraform-linters/setup-tflint@v1.1.0

    - name: Show version
      run: tflint --version

    - name: Init TFLint
      run: tflint --init

    - name: Run TFLint
      run: tflint --module -f compact